version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: losb
    container_name: losb-back
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery-worker
      - celery-beat
    networks:
      - django_network
    volumes:
      - static_volume:/app/static

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - django_network

  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    restart: always
    networks:
      - django_network

  celery-worker:
    build:
      context: .
    container_name: celery-worker
    command: celery -A app worker --loglevel=INFO
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - db
    networks:
      - django_network

  celery-beat:
    build:
      context: .
    container_name: celery-beat
    command: celery -A app beat --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - db
    networks:
      - django_network

networks:
  django_network:
    driver: bridge

volumes:
  db_data:
  static_volume:
