version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: losb
    container_name: losb-back
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - django_network
    volumes:
      - static_volume:/app/static

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - django_network

networks:
  django_network:
    driver: bridge

volumes:
  db_data:
  static_volume:
