name: Build backend image

on:
  push:
    branches:
      - "main"
      - "develop"
      - "dev"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Trigger infra repo
    steps:
      # extract branch name on pull request
      - name: Get branch names
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: "Run build backend action"
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: hqcamp
          repo: hardqode_edtech_infra
          github_token: ${{ secrets.ACTIONS_TOKEN }}
          github_user: KrasnovVitaliy
          workflow_file_name: build_backend.yml
          ref: main
          wait_interval: 10
          client_payload: '{"repo_name": "${{ vars.REPO_NAME }}","branch": "${{ steps.branch-names.outputs.current_branch }}"}'
          propagate_failure: false
          trigger_workflow: true
          wait_workflow: true
